# Generated by Django 2.1.3 on 2018-11-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_example_subcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': '제목', 'verbose_name_plural': '예제'},
        ),
    ]
